'---------------------------------------------------------------------------------------
' Class description: Functions
'---------------------------------------------------------------------------------------
Option Compare Database
Option Explicit

Private Const CurrentModName = "clsFunctions"

Private Sub Class_Initialize()
    '--- Konstruktor ---
End Sub

Private Sub Class_Terminate()
    '--- Destruktor ---
End Sub
